# Generated by Django 4.1.7 on 2025-11-19 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('activity', 'Activity Based'), ('streak', 'Streak Based'), ('distance', 'Distance Based'), ('duration', 'Duration Based'), ('social', 'Social/Team Based'), ('milestone', 'Milestone')], max_length=30)),
                ('requirement_type', models.CharField(choices=[('total_activities', 'Total Activities'), ('total_points', 'Total Points'), ('total_duration', 'Total Duration'), ('total_distance', 'Total Distance'), ('current_streak', 'Current Streak'), ('longest_streak', 'Longest Streak'), ('team_activities', 'Team Activities')], max_length=30)),
                ('requirement_value', models.PositiveIntegerField()),
                ('points_reward', models.PositiveIntegerField(default=0)),
                ('badge_icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_progress', models.FloatField(default=0.0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Challenge Participation',
                'verbose_name_plural': 'Challenge Participations',
            },
        ),
        migrations.CreateModel(
            name='WeeklyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('total_activities', 'Total Activities'), ('total_duration', 'Total Duration (minutes)'), ('total_distance', 'Total Distance (km)'), ('consistency', 'Daily Consistency'), ('variety', 'Activity Variety')], max_length=30)),
                ('target_value', models.FloatField()),
                ('points_reward', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(related_name='weekly_challenges', through='leaderboard.ChallengeParticipation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Challenge',
                'verbose_name_plural': 'Weekly Challenges',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('total_activities', models.PositiveIntegerField(default=0)),
                ('total_duration_minutes', models.PositiveIntegerField(default=0)),
                ('total_calories_burned', models.PositiveIntegerField(default=0)),
                ('total_distance_km', models.FloatField(default=0.0)),
                ('current_streak_days', models.PositiveIntegerField(default=0)),
                ('longest_streak_days', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('rank_position', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leaderboard Entry',
                'verbose_name_plural': 'Leaderboard Entries',
                'ordering': ['-total_points', '-total_activities'],
            },
        ),
        migrations.AddField(
            model_name='challengeparticipation',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.weeklychallenge'),
        ),
        migrations.AddField(
            model_name='challengeparticipation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('is_displayed', models.BooleanField(default=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Achievement',
                'verbose_name_plural': 'User Achievements',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='challengeparticipation',
            unique_together={('user', 'challenge')},
        ),
    ]
